# Generated by Django 5.2.1 on 2025-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current', models.FloatField(help_text='Current in Amperes')),
                ('power', models.FloatField(help_text='Power in Watts')),
                ('energy', models.FloatField(help_text='Energy in kWh')),
                ('building', models.CharField(default='Building A', max_length=100)),
            ],
        ),
    ]
